// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_tools.proto

package com.actoconfigure.test.model.rpc_package;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.actoconfigure.test.model.rpc_package.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
