// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_tools.proto

package com.actoconfigure.test.model.rpc_package;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.actoconfigure.test.model.rpc_package.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
